# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e221733a8347f768e92b679c8802ac512022c46871793be12226ee919d084db664680eedec0f240949e0dcdcddba8ee4b2adddda9678922d3b1e9673ca84b0fe

test:
  secret_key_base: 88d9e2215d7ba3029d7e95a72aa867684ce4325c90d2ee90c4f19e940c1f3e0e338a761a4b84b3e55917756e5134f1d988b7f3a832fb315483eef36008dbdc9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
